# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountThings' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for CountThings
  
  # Pods network
  pod 'Alamofire'
  # Pods Conection
  pod 'RealmSwift'
  # Pods Animations
  pod 'lottie-ios'
  
  
  target 'CountThingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountThingsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
