//
//  MainTablePresenterTests.swift
//  CountThings
//
//  Created by Danie Romero on 10/10/19.
//  Copyright (c) 2019 Dromero. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CountThings
import XCTest

class MainTablePresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: MainTablePresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupMainTablePresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupMainTablePresenter()
  {
    sut = MainTablePresenter()
  }
  
 
  // MARK: Tests
 
}
